In [103]:
import numpy as np
import pandas as pd
import time

In [15]:
a = lambda x,y:x*y
print(a(2,4))

8

In [11]:
#*arg or *kwarg
def kidcall(*kids):
    print(f"Hey {kids[2]} come here")

kidcall('Ravi''Roja','Radha','Rakul','Ruku')

Hey Rakul come here

In [19]:
#Iteration by iter and next() methods
X = [1,2,3,4,5,6,7]
X_it = iter(X)
print(next(X_it))
print(next(X_it))
print(next(X_it))
print(next(X_it))
print(next(X_it))
print(next(X_it))
print(next(X_it))
print(next(X_it))

1
2
3
4
5
6
7

StopIteration:

In [21]:
#Generators
def squr_root(limit):
    for num in range(limit,limit+1):
        yield num**2

for value in squr_root(5):
    print(value)

25

In [31]:
def even_generator(limit):
    for num in range(1, limit + 1):
        if num % 2 == 0:
            yield num
for even in even_generator(10):
    print(even)

2
4
6
8
10

In [85]:
#Slicing:
values = [5, 10, 15, 20, 25, 30, 35, 40]
print(X[2:7:2])
mix = [10, 'Python', 20.5, 'Slicing', 30, 'List', 40]
print(mix[1::2])
nums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
print(nums[-4:])
array = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
print(array[::-2])
text = "Python slicing techniques"
print(text[7:10])
print(text[1::3])
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)
print([col[1] for col in matrix])
data = [100, 200, 300, 400, 500, 600, 700, 800, 900]
print(data[:len(data)//2])
print(data[len(data)//2:])

[3, 5, 7]
['Python', 'Slicing', 'List']
[13, 15, 17, 19]
[20, 16, 12, 8, 4]
sli
yoscgenu
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[2, 5, 8]
[100, 200, 300, 400]
[500, 600, 700, 800, 900]

In [89]:
#Zip
a = [1, 2, 3]
b = [4, 5, 6]
c = [7, 8, 9]
result = list(zip(a,b,c))
print(result)
keys = ['name', 'age', 'city'] 
values = ['Alice', 25, 'NewYork']
result1 = dict(zip(keys,values))
print(result1)

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]
{'name': 'Alice', 'age': 25, 'city': 'NewYork'}

In [103]:
#Use of Else in try and except
def self_divide(a,b):
    try:
        return a/b
    except ZeroDivisionError :
        return ("Cant divide by zero")
    else:
        return ("Division is successfull")

self_divide(2,7)

0.2857142857142857

In [105]:
numbers = [12, -3, 45, -7, 10, -8, 30]
new_number = []
for num in numbers:
    if num>0:
        new_number.append(num**2)
    else:
        new_number.append(0)

print(new_number)

[144, 0, 2025, 0, 100, 0, 900]

In [109]:
for a in range(1,6):
    for b in range(1,6):
        if  a < b :
            print(a,b)

1 2
1 3
1 4
1 5
2 3
2 4
2 5
3 4
3 5
4 5

In [111]:
prices = [100, 150, 200, 250, 300]
new_prices = []
for num in prices:
    new_prices.append(num+num/10)

print(new_prices)

[110.0, 165.0, 220.0, 275.0, 330.0]

In [147]:
prices = [100, 150, 200, 250, 300]
increased_prices = []
for i, price in enumerate(prices):
    if i == 0:
        increased_prices.append(price)
    else:
        increased_prices.append(increased_prices[-1] * 1.1)

print(increased_prices)

[100, 110.00000000000001, 121.00000000000003, 133.10000000000005, 146.41000000000008]

In [163]:
def  calculate_stats(numbers):
    max_value = max(numbers)
    min_value = min(numbers)
    avg_value = sum(numbers)/len(numbers)
    return max_value,min_value,avg_value

numbers = [1009,156,10653,106538]
max_val,min_val,avg_val=calculate_stats(numbers)
print(f"max value is {max_val},min value is {min_val} and avg value is {avg_val}")

max value is 106538,min value is 156 and avg value is 29589.0

In [6]:
def calling(name,age,city='Unknown'):
    print(f"name:{name},age:{age},city:{city}")

calling('Vamshi','30')
calling('Vamshi','30','Hyd')

name:Vamshi,age:30,city:Unknown
name:Vamshi,age:30,city:Hyd

In [10]:
def order_food(main_dish, drink, dessert='ice cream'):
    print(f"main_dish:{main_dish},drink:{drink},dessert:{dessert}")

order_food('Rice_Bowle','Water','Keer')

main_dish:Rice_Bowle,drink:Water,dessert:Keer

In [18]:
def sum_all(*args):
    return sum(args)

print(sum_all())
print(sum_all(19,29,29))
print(sum_all(19))

0
77
19

In [20]:
def build_profile(**kwargs):
    for key,value in kwargs.items():
        print(f"{key}:{value}")

build_profile(name="Alice", age=30, city="New York")

name:Alice
age:30
city:New York

In [22]:
numbers = [1, 2, 3, 4, 5]
result = [x**2 for x in numbers]
print(result)

[1, 4, 9, 16, 25]

In [24]:
numbers = [1, 2, 3, 4,5, 6, 7, 8, 9]
even = [x for x in numbers if x%2==0]
print(even)

[2, 4, 6, 8]

In [26]:
words = ['apple', 'banana', 'cherry', 'date']
result = [x for x in words if len(x)>5]
print(result)

['banana', 'cherry']

In [36]:
result = [(a,b,a*b) for a in range(1,4) for b in range(1,4)]
print(result)

[(1, 1, 1), (1, 2, 2), (1, 3, 3), (2, 1, 2), (2, 2, 4), (2, 3, 6), (3, 1, 3), (3, 2, 6), (3, 3, 9)]

In [46]:
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
result = [key for key,value in data.items() if value%2==0]
print(result)

['b', 'd']

In [48]:
add = lambda x,y:x+y
print(add(10,5))

15

In [58]:
numbers = [1, 2, 3, 4, 5, 6]
result = filter(lambda x:x%2==0,numbers)
print(list(result))

[2, 4, 6]

In [64]:
names = ['Alice', 'bob', 'Anna', 'Mike']
result = list(filter(lambda x:x.lower().startswith('a'),names))
print(result)

['Alice', 'Anna']

In [68]:
points = [(2, 3), (4, 1), (5, 2), (1, 6)]
result = sorted(points,key=lambda x:x[1])
print(result)

[(4, 1), (5, 2), (2, 3), (1, 6)]

In [70]:
numbers = [1, 2, 3, 4,5]
sq = list(map(lambda x:x**2,numbers))
print(sq)

[1, 4, 9, 16, 25]

In [72]:
points = [(2, 3), (4, 1), (5, 2), (1, 6)]
sorted_point = sorted(points,key=lambda x:x[1])
print(sorted_point)

[(4, 1), (5, 2), (2, 3), (1, 6)]

In [1]:
students = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age':
22}, {'name': 'Charlie', 'age': 23}]
sorted_point = sorted(students,keys = lambda x:x['age'])
print(sorted_point)

[{'name': 'Bob', 'age': 22}, {'name': 'Charlie', 'age': 23}, {'name': 'Alice', 'age': 25}]

In [5]:
scores = {'Alice': 90, 'Bob': 85, 'Charlie': 95}
sorted_point = sorted(scores.items(),key=lambda x:x[1])
print(sorted_point)

[('Bob', 85), ('Alice', 90), ('Charlie', 95)]

In [7]:
fruits = ['apple', 'banana', 'fig', 'kiwi', 'cherry']
sorted_point = sorted(fruits,key=lambda x:len(x))
print(sorted_point)

['fig', 'kiwi', 'apple', 'banana', 'cherry']

In [13]:
data = [('apple', 2), ('banana', 2), ('cherry', 1), ('date', 3)]
sorted_point = sorted(data,key=lambda x:(x[1],x[0]))
print(sorted_point)

[('cherry', 1), ('apple', 2), ('banana', 2), ('date', 3)]

In [ ]:
#Use of key in lambda sorted
# Purpose of lambda Functions: lambda functions allow for quick, anonymous function
# definitions, useful when we need a simple function temporarily, especially within functions
# like sorted() or map() where only a small transformation is required.
# How key in sorted() Works: The key parameter allows specifying a function (often a lambda)
# that computes a value for sorting. Instead of comparing items directly, sorted() compares the
# results of applying the key to each item.
# Example Scenario: Sorting a list of dictionaries by a specific field (e.g., age), where each
# dictionary represents a person. Using sorted(people, key=lambda x: x['age']) is simpler and
# more readable than writing a for loop to sort by extracting and comparing age.

In [ ]:
# compare list List comprehensions and for loop
# Difference: A list comprehension is a compact syntax for generating a new list from an
# existing iterable. It combines looping and conditional logic into a single line, making code
# shorter and often faster since it avoids some overhead associated with a for loop.
# When List Comprehensions are Preferred: When the goal is to create a new list by
# transforming or filtering elements from an iterable, list comprehensions provide a concise,
# readable syntax (e.g., [x ** 2 for x in range(10) if x % 2 == 0]).
# When for Loops are Preferred: If the operation involves complex logic, multiple actions
# within each iteration, or updates to multiple variables, a traditional for loop may be clearer
# and easier to debug, as list comprehensions become harder to read and maintain in these
# cases.

In [29]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
second_row = arr[1]
print(second_row)
third_row_second_col = arr[2][1]
print(third_row_second_col)
First_two_col_all_row = arr[:,:2]
print(First_two_col_all_row)

[40 50 60]
80
[[10 20]
 [40 50]
 [70 80]]

In [37]:
arr = np.array([50, 10, 40, 20, 30])
assc = np.sort(arr)
print(assc)
desc = np.sort(arr)[::-1]
print(desc)
arr_2d = np.array([[3, 1, 2], [9, 7, 8]])
sort_row = np.sort(arr_2d,axis=1)
print(sort_row)

[10 20 30 40 50]
[50 40 30 20 10]
[[1 2 3]
 [7 8 9]]

In [41]:
arr = np.array([40, 10, 50, 20, 30])
assc = np.argsort(arr)
print(assc)
desc = np.argsort(arr)[::-1]
print(desc)
arr_2d =  np.array([[2, 0, 1], [5, 3, 4]])
sort_row = np.argsort(arr_2d,axis=1)
print(sort_row)

[1 3 4 0 2]
[2 0 4 3 1]
[[1 2 0]
 [1 2 0]]

In [45]:
import pandas as pd
data = {'A': [10, 20, 30, 40],
'B': [50, 60, 70, 80],
'C': [90, 100, 110, 120],
'D': [130, 140, 150, 160]}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df)

    A   B    C    D
a  10  50   90  130
b  20  60  100  140
c  30  70  110  150
d  40  80  120  160

In [53]:
result = df.loc[['b','d'],['A','C']]
print(result)

    A    C
b  20  100
d  40  120

In [55]:
result = df[df['A']>df['B']]
print(result)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [63]:
result = df.iloc[-2:,:2]
print(result)

    A   B
c  30  70
d  40  80

In [65]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [25, 30, 35, 40],
'Score': [88, 92, 85, 95]}
df = pd.DataFrame(data)
print(df)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     85
3    David   40     95

In [69]:
result = df[(df['Age']>30) & (df['Age']<90)]
print(result)

      Name  Age  Score
2  Charlie   35     85
3    David   40     95

In [75]:
result = df[(df['Name'].str.startswith('A')) | (df['Name'].str.endswith('d'))]
print(result)

    Name  Age  Score
0  Alice   25     88
3  David   40     95

In [77]:
result = df[df['Score'].between(85,95)]
print(result)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     85
3    David   40     95

In [113]:
import pandas as pd
data = {'Product': ['A', 'B', 'C', 'D'],
'Price': [100, 200, 300, 400],
'Stock': [50, 60, 70, 80]}
df = pd.DataFrame(data)
print(df)

  Product  Price  Stock
0       A    100     50
1       B    200     60
2       C    300     70
3       D    400     80

In [89]:
df.loc[df['Stock']>60,'Price']*=1.1
print(df)

  Product  Price  Stock
0       A  100.0     50
1       B  200.0     60
2       C  363.0     70
3       D  484.0     80

In [95]:
df.loc[df['Price'] < 200, 'Stock'] = 'Out of Stock'
print(df)

  Product  Price         Stock
0       A  100.0  Out of Stock
1       B  200.0            60
2       C  363.0            70
3       D  484.0            80

C:\Users\VamC\AppData\Local\Temp\ipykernel_17884\2298090702.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Out of Stock' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Price'] < 200, 'Stock'] = 'Out of Stock'

In [115]:
mean_price = df['Price'].mean()
df.loc[df['Stock'] < 70, 'Price'] = mean_price
print(df)

  Product  Price  Stock
0       A    250     50
1       B    250     60
2       C    300     70
3       D    400     80

In [3]:
import pandas as pd
data = {
'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank'],
'Age': [25, 30, 35, 40, 28, 45, 50, 33],
'Salary': [50000, 60000, 55000, 65000, 48000, 70000, 75000, 62000],
'Department': ['HR', 'Finance', 'IT', 'IT', 'Finance', 'HR', 'IT', 'Finance']
}
df = pd.DataFrame(data)
print(df)

  Employee  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000    Finance
2  Charlie   35   55000         IT
3    David   40   65000         IT
4      Eve   28   48000    Finance
5    Frank   45   70000         HR
6    Grace   50   75000         IT
7     Hank   33   62000    Finance

In [127]:
def cat_age(age):
    if age<30:
        return 'Junior'
    elif 30 <= age <= 40:
        return 'Mid'
    elif age>40:
        return 'Senior'

df['age_group'] = df['Age'].apply(cat_age)
print(df[['Employee','Age','age_group']])

  Employee  Age age_group
0    Alice   25    Junior
1      Bob   30       Mid
2  Charlie   35       Mid
3    David   40       Mid
4      Eve   28    Junior
5    Frank   45    Senior
6    Grace   50    Senior
7     Hank   33       Mid

In [135]:
df['Salary']=df.apply(lambda row:row['Salary']*1.1 if row['Department']=='IT' else row['Salary'],axis=1)
print(df)

  Employee  Age   Salary Department age_group
0    Alice   25  50000.0         HR    Junior
1      Bob   30  60000.0    Finance       Mid
2  Charlie   35  60500.0         IT       Mid
3    David   40  71500.0         IT       Mid
4      Eve   28  48000.0    Finance    Junior
5    Frank   45  70000.0         HR    Senior
6    Grace   50  82500.0         IT    Senior
7     Hank   33  62000.0    Finance       Mid

In [139]:
df['Tax']=df.apply(lambda row:row['Salary']*0.5 if row['Department']=='HR' else row['Salary']*0.8,axis=1)
print(df)

  Employee  Age   Salary Department age_group      Tax
0    Alice   25  50000.0         HR    Junior  25000.0
1      Bob   30  60000.0    Finance       Mid  48000.0
2  Charlie   35  60500.0         IT       Mid  48400.0
3    David   40  71500.0         IT       Mid  57200.0
4      Eve   28  48000.0    Finance    Junior  38400.0
5    Frank   45  70000.0         HR    Senior  35000.0
6    Grace   50  82500.0         IT    Senior  66000.0
7     Hank   33  62000.0    Finance       Mid  49600.0

In [15]:
for index,row in df.iterrows():
    print(f"Emp:{row['Employee']},Age:{row['Age']},Sal:{row['Salary']}")

Emp:Alice,Age:25,Sal:50000
Emp:Bob,Age:30,Sal:60000
Emp:Charlie,Age:35,Sal:55000
Emp:David,Age:40,Sal:65000
Emp:Eve,Age:28,Sal:48000
Emp:Frank,Age:45,Sal:70000
Emp:Grace,Age:50,Sal:75000
Emp:Hank,Age:33,Sal:62000

In [19]:
dept_sal = {}
for index,row in df.iterrows():
    dept = row['Department']
    if dept not in dept_sal:
        dept_sal[dept]=[]
    dept_sal[dept].append(row['Salary'])

for dept,salary in dept_sal.items():
    avg_sal = sum(salary)/len(salary)
    print(f"avg sal for {dept}:{avg_sal}")

avg sal for HR:50000.0
avg sal for Finance:56666.666666666664
avg sal for IT:60000.0
avg sal for Consulting:68875.0

In [21]:
dept_salaries = {}
for index, row in df.iterrows():
    dept = row['Department']
    if dept not in dept_salaries:
        dept_salaries[dept] = []
    dept_salaries[dept].append(row['Salary'])

for dept, salaries in dept_salaries.items():
    avg_salary = sum(salaries) / len(salaries)
    print(f"Average Salary in {dept}: {avg_salary}")

Average Salary in HR: 50000.0
Average Salary in Finance: 56666.666666666664
Average Salary in IT: 60000.0
Average Salary in Consulting: 68875.0

In [29]:
dept_avg = {dept: sum(salaries) / len(salaries) for dept, salaries in
dept_salaries.items()}
for index,row in df.iterrows():
    if row['Salary'] > dept_avg[row['Department']]:
        print(f"{row['Employee']} has a salary above the department average.")

Bob has a salary above the department average.
David has a salary above the department average.
Grace has a salary above the department average.
Hank has a salary above the department average.

In [5]:
df.loc[df['Salary']>65000,'Department']='Consulting'
print(df)

  Employee  Age  Salary  Department
0    Alice   25   50000          HR
1      Bob   30   60000     Finance
2  Charlie   35   55000          IT
3    David   40   65000          IT
4      Eve   28   48000     Finance
5    Frank   45   70000  Consulting
6    Grace   50   75000  Consulting
7     Hank   33   62000     Finance

In [7]:
df.loc[df['Age']>40,'Salary']*=0.95
print(df)

  Employee  Age  Salary  Department
0    Alice   25   50000          HR
1      Bob   30   60000     Finance
2  Charlie   35   55000          IT
3    David   40   65000          IT
4      Eve   28   48000     Finance
5    Frank   45   66500  Consulting
6    Grace   50   71250  Consulting
7     Hank   33   62000     Finance

In [41]:
avg = dept_avg['Finance']
df.loc[df['Department']=='Finance','Salary']=avg
print(df)

  Employee  Age        Salary  Department
0    Alice   25  50000.000000          HR
1      Bob   30  56666.666667     Finance
2  Charlie   35  55000.000000          IT
3    David   40  65000.000000          IT
4      Eve   28  56666.666667     Finance
5    Frank   45  66500.000000  Consulting
6    Grace   50  71250.000000  Consulting
7     Hank   33  56666.666667     Finance

C:\Users\VamC\AppData\Local\Temp\ipykernel_1668\3837863945.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '56666.666666666664' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Department']=='Finance','Salary']=avg

In [43]:
import pandas as pd
data = {
'Department': ['HR', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'Finance', 'IT'],
'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank'],
'Age': [25, 30, 35, 40, 28, 45, 50, 33],
'Salary': [50000, 60000, 55000, 65000, 48000, 70000, 75000, 62000]
}
df = pd.DataFrame(data)
print(df)

  Department Employee  Age  Salary
0         HR    Alice   25   50000
1    Finance      Bob   30   60000
2         IT  Charlie   35   55000
3         HR    David   40   65000
4    Finance      Eve   28   48000
5         IT    Frank   45   70000
6    Finance    Grace   50   75000
7         IT     Hank   33   62000

In [49]:
result = df.groupby('Department').agg({'Salary':'sum','Age':'min'})
print(result)

            Salary  Age
Department
Finance     183000   28
HR          115000   25
IT          187000   33

In [53]:
result = df.groupby('Department').agg({'Salary':'mean','Age':'min'})
print(result)

                  Salary  Age
Department
Finance     61000.000000   28
HR          57500.000000   25
IT          62333.333333   33

In [67]:
df['Dept_Avg_Salary']=df.groupby('Department')['Salary'].transform('mean')
df_above_age = df[df['Salary']>df['Dept_Avg_Salary']][['Department','Employee','Salary','Dept_Avg_Salary']]
print(df_above_age)

  Department Employee  Salary  Dept_Avg_Salary
3         HR    David   65000     57500.000000
5         IT    Frank   70000     62333.333333
6    Finance    Grace   75000     61000.000000

In [81]:
df['Dept_Avg_Age']=df.groupby('Department')['Age'].transform('mean')
df['Age_Relative_to_Avg']=df.apply(lambda x:'Above Avg' if x['Age']>x['Dept_Avg_Age'] else 'Below Avg',axis=1)
print(df[['Department','Employee','Age','Dept_Avg_Age','Age_Relative_to_Avg']])

  Department Employee  Age  Dept_Avg_Age Age_Relative_to_Avg
0         HR    Alice   25     32.500000           Below Avg
1    Finance      Bob   30     36.000000           Below Avg
2         IT  Charlie   35     37.666667           Below Avg
3         HR    David   40     32.500000           Above Avg
4    Finance      Eve   28     36.000000           Below Avg
5         IT    Frank   45     37.666667           Above Avg
6    Finance    Grace   50     36.000000           Above Avg
7         IT     Hank   33     37.666667           Below Avg

In [93]:
df['Max_Dept_Sal']=df.groupby('Department')['Salary'].transform('max')
df['Pct_Diff_from_Max'] = ((df['Max_Dept_Sal']-df['Salary'])/df['Max_Dept_Sal'])
print(df[['Department','Employee','Age','Max_Dept_Sal','Pct_Diff_from_Max']])

  Department Employee  Age  Max_Dept_Sal  Pct_Diff_from_Max
0         HR    Alice   25         65000           0.230769
1    Finance      Bob   30         75000           0.200000
2         IT  Charlie   35         70000           0.214286
3         HR    David   40         65000           0.000000
4    Finance      Eve   28         75000           0.360000
5         IT    Frank   45         70000           0.000000
6    Finance    Grace   50         75000           0.000000
7         IT     Hank   33         70000           0.114286

In [105]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.2.0-cp312-cp312-win_amd64.whl.metadata (6.2 kB)
Downloading mysql_connector_python-9.2.0-cp312-cp312-win_amd64.whl (16.1 MB)
   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
   --- ------------------------------------ 1.3/16.1 MB 6.7 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/16.1 MB 6.0 MB/s eta 0:00:03
   --------- ------------------------------ 3.9/16.1 MB 6.3 MB/s eta 0:00:02
   ------------- -------------------------- 5.5/16.1 MB 6.7 MB/s eta 0:00:02
   ---------------- ----------------------- 6.6/16.1 MB 6.4 MB/s eta 0:00:02
   -------------------- ------------------- 8.4/16.1 MB 6.7 MB/s eta 0:00:02
   ------------------------ --------------- 10.0/16.1 MB 6.7 MB/s eta 0:00:01
   ---------------------------- ----------- 11.5/16.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------- ------- 13.1/16.1 MB 7.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.9/16.1 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------- 16.1/16.1 MB 6.9 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.2.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [119]:
import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="1234",
    database="sakila"
)

In [129]:
df = pd.read_sql_query("SELECT * FROM sakila.actor",connection)
df

C:\Users\VamC\AppData\Local\Temp\ipykernel_1668\3000957715.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM sakila.actor",connection)

OperationalError: MySQL Connection not available.

In [127]:
connection.close()

In [3]:
x = lambda x,y:x+y
print(x(5,6))

11

In [9]:
for x in range(1,11):
    if x==3:
        pass
    elif x==4:
        continue
    elif x==7:
        break
    print(x)

1
2
3
5
6

In [13]:
x = [1,2,3,4,5,8]

it = iter(x)
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))

1
2
3
4
5
8

StopIteration:

In [3]:
def sample_generater(limit):
    num = 0
    while num<limit:
        yield num
        num+=1

for x in sample_generater(7):
    print(x)

0
1
2
3
4
5
6

In [33]:
def squre(limit):
    for x in range(1,limit+1):
        yield x**2

for i in squre(7):
    print(i)

1
4
9
16
25
36
49

In [35]:
def even(limit):
    for num in range(1,limit+1):
        if num%2 == 0:
            yield x

for i in even(10):
    print(i)

120
120
120
120
120

In [31]:
def generate_factorial(limit):
    fact = 1
    for num in range(1,limit+1):
        fact*=num
        yield fact

for x in generate_factorial(5):
    print(x)

1
2
6
24
120

In [37]:
values = [5, 10, 15, 20, 25, 30, 35, 40]
values[2:7:2]

[15, 25, 35]

In [49]:
mix = [10, 'Python', 20.5, 'Slicing', 30, 'List', 40]
mix[1::2]

['Python', 'Slicing', 'List']

In [51]:
nums = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
nums[-4:]

[13, 15, 17, 19]

In [53]:
array = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
array[::-2]

[20, 16, 12, 8, 4]

In [57]:
text = "Python slicing techniques"
text[1::3]

'yoscgenu'

In [61]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[col[1] for col in matrix]

[2, 5, 8]

In [69]:
data = [100, 200, 300, 400, 500, 600, 700, 800, 900]
[data[:len(data)//2],data[len(data)//2:]]

[[100, 200, 300, 400], [500, 600, 700, 800, 900]]

In [71]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [7, 8, 9]
list(zip(a,b,c))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [73]:
keys = ['name', 'age', 'city']
values = ['Alice', 25, 'NewYork']
dict(zip(keys,values))

{'name': 'Alice', 'age': 25, 'city': 'NewYork'}

In [75]:
def division(a,b):
    try:
        return a/b
    except ZeroDivisionError:
        return 'Cannot divide by zero'

In [83]:
division(10,0)

'Cannot divide by zero'

In [85]:
def finding(lst,ind):
    try:
        return lst[ind]
    except (IndexError,TypeError):
        return 'Invalid Index'

In [91]:
finding([1,2,3,4,5,6],8)

'Invalid Index'

In [97]:
def div(a,b):
    try:
        return a/b
    except ZeroDivisionError:
        return 'Cannot divide by zero'
    finally:
        print('Complete Transcation')

In [101]:
div(100,5)

Complete Transcation

20.0

In [111]:
numbers = [12, -3, 45, -7, 10, -8, 30]
new = []
for x in numbers:
    if x > 0:
        new.append(x**2)
    else:
        new.append(0)

print(new)

[144, 0, 2025, 0, 100, 0, 900]

In [117]:
for x in range(1,6):
    for y in range(x+1,6):
        if x<y:
            print(x,y)

1 2
1 3
1 4
1 5
2 3
2 4
2 5
3 4
3 5
4 5

In [121]:
prices = [100, 150, 200, 250, 300]
new = []

for i,price in enumerate(prices):
    if i==0:
        new.append(price)
    else:
        new.append(new[-1]*1.1)

print(new)

[100, 110.00000000000001, 121.00000000000003, 133.10000000000005, 146.41000000000008]

In [123]:
def cal_tran(numbers):
    max_value = max(numbers)
    min_value = min(numbers)
    avg_value = sum(numbers)/len(numbers)
    return max_value,min_value,avg_value

numbers = [1,2,3,4,5,6,7,8,9]
maxi,mini,avgi = cal_tran(numbers)
print(f'max:{maxi},min:{mini},avg:{avgi}')

max:9,min:1,avg:5.0

In [127]:
def describe_person(name,age,city='Unknown'):
    print(f'name:{name},age:{age},city:{city}')

describe_person('Vamshi','20')
describe_person('Vamshi','20','Hyd')

name:Vamshi,age:20,city:Unknown
name:Vamshi,age:20,city:Hyd

In [133]:
def order_food(main_dish,drink,dessert='ice cream'):
    print(f'main_dish:{main_dish},drink:{drink},dessert:{dessert}')

order_food('burger','soda',dessert='cake')

main_dish:burger,drink:soda,dessert:cake

In [141]:
def sum_all(*args):
    return sum(args)

print(sum_all(10,2,40,6))
print(sum_all(10,10,6))
print(sum_all(10,2))

58
26
12

In [147]:
def build_profile(**kwargs):
    for key,value in kwargs.items():
        print(f'{key}:{value}')

print(build_profile(name = 'Alice',age=20,city='Hyd'))
print(build_profile(name = 'Vamshi',Role='HR'))

name:Alice
age:20
city:Hyd
None
name:Vamshi
Role:HR
None

In [149]:
numbers = [1, 2, 3, 4, 5]
new = []

for x in numbers:
    new.append(x**2)

print(new)

[1, 4, 9, 16, 25]

In [151]:
numbers = [1, 2, 3, 4, 5]
result = [x**2 for x in numbers]
print(result)

[1, 4, 9, 16, 25]

In [153]:
numbers = [1, 2, 3, 4,5, 6, 7, 8, 9]
result = [x for x in numbers if x%2==0]
print(result)

[2, 4, 6, 8]

In [155]:
words = ['apple', 'banana', 'cherry', 'date']
result = [x for x in words if len(x) > 5]
print(result)

['banana', 'cherry']

In [157]:
result = [(a,b,a*b) for a in range(1,4) for b in range(1,4)]
print(result)

[(1, 1, 1), (1, 2, 2), (1, 3, 3), (2, 1, 2), (2, 2, 4), (2, 3, 6), (3, 1, 3), (3, 2, 6), (3, 3, 9)]

In [161]:
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
result = [key for key,value in data.items() if value%2==0]
print(result)

['b', 'd']

In [163]:
x = lambda x,y:x+y
print(x(10,5))

15

In [167]:
numbers = [1, 2, 3, 4, 5, 6]
even = list(filter(lambda x:x%2==0,numbers))
print(even)

[2, 4, 6]

In [173]:
names = ['Alice', 'bob', 'Anna', 'Mike']
x = tuple(filter(lambda x:x.lower().startswith('a'),names))
print(x)

('Alice', 'Anna')

In [177]:
points = [(2, 3), (4, 1), (5, 2), (1, 6)]
x=list(sorted(points,key=lambda x:x[1]))
print(x)

[(4, 1), (5, 2), (2, 3), (1, 6)]

In [179]:
numbers = [1, 2, 3, 4,5]
x = list(map(lambda x:x**2,numbers))
print(x)

[1, 4, 9, 16, 25]

In [181]:
points = [(2, 3), (4, 1), (5, 2), (1, 6)]
sort = sorted(points,key=lambda x:x[1])
print(sort)

[(4, 1), (5, 2), (2, 3), (1, 6)]

In [183]:
students = [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age':22}, {'name': 'Charlie', 'age': 23}]
x = sorted(students,key=lambda x:x['age'])
print(x)

[{'name': 'Bob', 'age': 22}, {'name': 'Charlie', 'age': 23}, {'name': 'Alice', 'age': 25}]

In [187]:
scores = {'Alice': 90, 'Bob': 85, 'Charlie': 95}
sorted(scores.items(),key=lambda x:x[1])

[('Bob', 85), ('Alice', 90), ('Charlie', 95)]

In [189]:
fruits = ['apple', 'banana', 'fig', 'kiwi', 'cherry']
sorted(fruits,key=lambda x:len(x))

['fig', 'kiwi', 'apple', 'banana', 'cherry']

In [191]:
data = [('apple', 2), ('banana', 2), ('cherry', 1), ('date', 3)]
sorted(data,key=lambda x:[x[1],x[0]])

[('cherry', 1), ('apple', 2), ('banana', 2), ('date', 3)]

In [201]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[1])
print(arr[2,1])
print(arr[:,:2])

[40 50 60]
80
[[10 20]
 [40 50]
 [70 80]]

In [215]:
arr1 = np.array([50, 10, 40, 20, 30])
print(np.sort(arr1))
print(np.sort(arr1)[::-1])
arr_2d = np.array([[3, 1, 2], [9, 7, 8]])
print(np.sort(arr_2d,axis=1))

[10 20 30 40 50]
[50 40 30 20 10]
[[1 2 3]
 [7 8 9]]

In [221]:
arr2 = np.array([40, 10, 50, 20, 30])
print(np.argsort(arr2))
print(np.argsort(arr2)[::-1])
arr_2d = np.array([[2, 0, 1], [5, 3, 4]])
print(np.argsort(arr_2d[:,0]))

[1 3 4 0 2]
[2 0 4 3 1]
[0 1]

In [223]:
data = {'A': [10, 20, 30, 40],
'B': [50, 60, 70, 80],
'C': [90, 100, 110, 120],
'D': [130, 140, 150, 160]}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df)

    A   B    C    D
a  10  50   90  130
b  20  60  100  140
c  30  70  110  150
d  40  80  120  160

In [231]:
result = df.loc[['b','d'],['A','C']]
print(result)

    A    C
b  20  100
d  40  120

In [235]:
result = df.loc[df['A']>df['B']]
print(result)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [239]:
result = df.iloc[-2:,:2]
print(result)

    A   B
c  30  70
d  40  80

In [241]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
'Age': [25, 30, 35, 40],
'Score': [88, 92, 85, 95]}
df1 = pd.DataFrame(data)
print(df1)

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     85
3    David   40     95

In [249]:
result = df1[(df1['Age']>30) & (df1['Score']<90)]
print(result)

      Name  Age  Score
2  Charlie   35     85

In [255]:
result = df1[(df1['Name'].str.startswith('A'))|(df1['Name'].str.endswith('d'))]
print(result)

    Name  Age  Score
0  Alice   25     88
3  David   40     95

In [261]:
df1[df1['Score'].between(85,95)]

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     85
3    David   40     95

In [275]:
data = {'Product': ['A', 'B', 'C', 'D'],
'Price': [100, 200, 300, 400],
'Stock': [50, 60, 70, 80]}
df3 = pd.DataFrame(data)
print(df3)

  Product  Price  Stock
0       A    100     50
1       B    200     60
2       C    300     70
3       D    400     80

In [271]:
df3.loc[df3['Stock']>60,'Price']*=1.1
print(df3)

  Product  Price  Stock
0       A  100.0     50
1       B  200.0     60
2       C  363.0     70
3       D  484.0     80

In [273]:
df3.loc[df3['Price']>200,'Stock']='Out of Stock'
print(df3)

  Product  Price         Stock
0       A  100.0            50
1       B  200.0            60
2       C  363.0  Out of Stock
3       D  484.0  Out of Stock

C:\Users\VamC\AppData\Local\Temp\ipykernel_6416\669238040.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Out of Stock' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df3.loc[df3['Price']>200,'Stock']='Out of Stock'

In [279]:
mean_value = df3['Stock'].mean()
df3.loc[df3['Stock']<70,'Stock']=mean_value
print(df3)

  Product  Price  Stock
0       A    100     65
1       B    200     65
2       C    300     70
3       D    400     80

In [299]:
data = {
'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank'],
'Age': [25, 30, 35, 40, 28, 45, 50, 33],
'Salary': [50000, 60000, 55000, 65000, 48000, 70000, 75000, 62000],
'Department': ['HR', 'Finance', 'IT', 'IT', 'Finance', 'HR', 'IT', 'Finance']
}
df4 = pd.DataFrame(data)
print(df4)

  Employee  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000    Finance
2  Charlie   35   55000         IT
3    David   40   65000         IT
4      Eve   28   48000    Finance
5    Frank   45   70000         HR
6    Grace   50   75000         IT
7     Hank   33   62000    Finance

In [291]:
def cat_age(age):
    if age<30:
        return 'Junior'
    elif 30<=age<=40:
        return 'Mid'
    else:
        return 'Senior'

df4['Age_Cat']=df4['Age'].apply(cat_age)
print(df4[['Employee','Age','Age_Cat']])

  Employee  Age Age_Cat
0    Alice   25  Junior
1      Bob   30     Mid
2  Charlie   35     Mid
3    David   40     Mid
4      Eve   28  Junior
5    Frank   45  Senior
6    Grace   50  Senior
7     Hank   33     Mid

In [297]:
df4.loc[df4['Department']=='IT','Salary']*=1.1
print(df4)

  Employee  Age   Salary Department Age_Cat
0    Alice   25  50000.0         HR  Junior
1      Bob   30  60000.0    Finance     Mid
2  Charlie   35  66550.0         IT     Mid
3    David   40  78650.0         IT     Mid
4      Eve   28  48000.0    Finance  Junior
5    Frank   45  70000.0         HR  Senior
6    Grace   50  90750.0         IT  Senior
7     Hank   33  62000.0    Finance     Mid

In [307]:
df4.apply(lambda row:row['Salary']*1.1 if row['Department']=='IT' else row['Salary'],axis=1)
print(df4)

  Employee  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000    Finance
2  Charlie   35   55000         IT
3    David   40   65000         IT
4      Eve   28   48000    Finance
5    Frank   45   70000         HR
6    Grace   50   75000         IT
7     Hank   33   62000    Finance

In [309]:
df4.apply(lambda row:row['Salary']*0.05 if row['Department']=='HR' else row['Salary']*0.08,axis=1)
print(df4)

  Employee  Age  Salary Department
0    Alice   25   50000         HR
1      Bob   30   60000    Finance
2  Charlie   35   55000         IT
3    David   40   65000         IT
4      Eve   28   48000    Finance
5    Frank   45   70000         HR
6    Grace   50   75000         IT
7     Hank   33   62000    Finance

In [313]:
for index,row in df4.iterrows():
    print(f'Name:{row['Employee']},Age:{row['Age']},Salary:{row['Salary']},Dept:{row['Department']}')

Name:Alice,Age:25,Salary:50000,Dept:HR
Name:Bob,Age:30,Salary:60000,Dept:Finance
Name:Charlie,Age:35,Salary:55000,Dept:IT
Name:David,Age:40,Salary:65000,Dept:IT
Name:Eve,Age:28,Salary:48000,Dept:Finance
Name:Frank,Age:45,Salary:70000,Dept:HR
Name:Grace,Age:50,Salary:75000,Dept:IT
Name:Hank,Age:33,Salary:62000,Dept:Finance

In [323]:
depart = {}
for index,row in df4.iterrows():
    dept = row['Department']
    if dept not in depart:
        depart[dept]=[]
    depart[dept].append(row['Salary'])

for dept,sal in depart.items():
    avg_sal = sum(sal)/len(sal)
    print(f'Avg sal of dept {dept}:{avg_sal}')

Avg sal of dept HR:60000.0
Avg sal of dept Finance:56666.666666666664
Avg sal of dept IT:65000.0

In [337]:
dept_avg = {dept:sum(sal)/len(sal) for dept,sal in depart.items()}
for index,row in df4.iterrows():
    if row['Salary']>dept_avg[row['Department']]:
        print(f'{row['Employee']} having salary greater than avg')

Bob having salary greater than avg
Frank having salary greater than avg
Grace having salary greater than avg
Hank having salary greater than avg

In [341]:
df4.loc[df4['Salary']>65000,'Department']='Consulting'
print(df4)

  Employee  Age  Salary  Department
0    Alice   25   50000          HR
1      Bob   30   60000     Finance
2  Charlie   35   55000          IT
3    David   40   65000          IT
4      Eve   28   48000     Finance
5    Frank   45   70000  Consulting
6    Grace   50   75000  Consulting
7     Hank   33   62000     Finance

In [345]:
df4.loc[df4['Age']>40,'Salary']*=0.95
print(df4)

  Employee  Age   Salary  Department
0    Alice   25  50000.0          HR
1      Bob   30  60000.0     Finance
2  Charlie   35  55000.0          IT
3    David   40  65000.0          IT
4      Eve   28  48000.0     Finance
5    Frank   45  63175.0  Consulting
6    Grace   50  67687.5  Consulting
7     Hank   33  62000.0     Finance

C:\Users\VamC\AppData\Local\Temp\ipykernel_6416\158698673.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[63175.  67687.5]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df4.loc[df4['Age']>40,'Salary']*=0.95

In [349]:
avg_sal = dept_avg['Finance']
df4.loc[df4['Department']=='Finance','Salary']=avg_sal
print(df4)

  Employee  Age        Salary  Department
0    Alice   25  50000.000000          HR
1      Bob   30  56666.666667     Finance
2  Charlie   35  55000.000000          IT
3    David   40  65000.000000          IT
4      Eve   28  56666.666667     Finance
5    Frank   45  63175.000000  Consulting
6    Grace   50  67687.500000  Consulting
7     Hank   33  56666.666667     Finance

In [359]:
data = {
'Department': ['HR', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'Finance', 'IT'],
'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hank'],
'Age': [25, 30, 35, 40, 28, 45, 50, 33],
'Salary': [50000, 60000, 55000, 65000, 48000, 70000, 75000, 62000]
}
df5 = pd.DataFrame(data)
print(df5)

  Department Employee  Age  Salary
0         HR    Alice   25   50000
1    Finance      Bob   30   60000
2         IT  Charlie   35   55000
3         HR    David   40   65000
4    Finance      Eve   28   48000
5         IT    Frank   45   70000
6    Finance    Grace   50   75000
7         IT     Hank   33   62000

In [363]:
result = df5.groupby('Department').agg({'Salary':'mean','Age':'max'})
print(result)

                  Salary  Age
Department
Finance     61000.000000   50
HR          57500.000000   40
IT          62333.333333   45

In [365]:
result = df5.groupby('Department').agg({'Salary':'sum','Age':'min'})
print(result)

            Salary  Age
Department
Finance     183000   28
HR          115000   25
IT          187000   33

In [373]:
df5['Avg_sal'] = df5.groupby('Department')['Salary'].transform('mean')
result = df5[df5['Salary']>df5['Avg_sal']][['Employee','Salary','Avg_sal']]
print(result)

  Employee  Salary       Avg_sal
3    David   65000  57500.000000
5    Frank   70000  62333.333333
6    Grace   75000  61000.000000

In [379]:
df5['Dept_Avg_Age'] = df5.groupby('Department')['Age'].transform('mean')
df5['Age_Relative_to_Avg'] = df5.apply(lambda x: 'Above Avg' if x['Age'] > x['Dept_Avg_Age']
else 'Below Avg', axis=1)
print(result)

  Employee  Salary       Avg_sal
3    David   65000  57500.000000
5    Frank   70000  62333.333333
6    Grace   75000  61000.000000

In [381]:
df5['High'] = df5.groupby('Department')['Salary'].transform('max')
df5['Pct_Diff_from_Max']=(df5['High']-df5['Salary'])/df5['High']
df5

,Department,Employee,Age,Salary,Avg_sal,Avg_age,Dept_Avg_Age,Age_Relative_to_Avg,High,Pct_Diff_from_Max
0,HR,Alice,25,50000,57500.000000,32.500000,32.500000,Below Avg,65000,0.230769
1,Finance,Bob,30,60000,61000.000000,36.000000,36.000000,Below Avg,75000,0.200000
2,IT,Charlie,35,55000,62333.333333,37.666667,37.666667,Below Avg,70000,0.214286
3,HR,David,40,65000,57500.000000,32.500000,32.500000,Above Avg,65000,0.000000
4,Finance,Eve,28,48000,61000.000000,36.000000,36.000000,Below Avg,75000,0.360000
5,IT,Frank,45,70000,62333.333333,37.666667,37.666667,Above Avg,70000,0.000000
6,Finance,Grace,50,75000,61000.000000,36.000000,36.000000,Above Avg,75000,0.000000
7,IT,Hank,33,62000,62333.333333,37.666667,37.666667,Below Avg,70000,0.114286