In [201]:
import pandas as pd
import numpy as np

In [202]:
#Create a Series
S_sclar = pd.Series(10,index=['a','b','c','d','e'])
print(S_sclar)

a    10
b    10
c    10
d    10
e    10
dtype: int64

In [203]:
New_scalar = pd.Series(10)
print(New_scalar)

0    10
dtype: int64

In [204]:
data = [10,20,30,40,50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [205]:
data = np.array([10,20,30,40,50])
data_s = pd.Series(data,index=['a','b','c','d','e'])
print(data_s)

a    10
b    20
c    30
d    40
e    50
dtype: int32

In [206]:
data_dict = {'a':10,'b':20,'c':30,'d':40,'e':50}
s_dict = pd.Series(data_dict)
print(s_dict)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [207]:
#Indexing
print(S_sclar[0])
print(S_sclar[:3])
print(S_sclar['a'])

10
a    10
b    10
c    10
dtype: int64
10

C:\Users\VamC\AppData\Local\Temp\ipykernel_15076\1988142548.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(S_sclar[0])

In [208]:
data = ['Del','DC','London','paris']
index = ['Ind','USA','UK','Frn']
New = pd.Series(data,index = index)
print(New)

Ind       Del
USA        DC
UK     London
Frn     paris
dtype: object

In [209]:
print(New.index)
print(New.values)
print(New.name)
print(New.shape)
print(New.size)
print(New.empty)
print(New.hasnans)
print(New.is_unique)
print(New.ndim)

Index(['Ind', 'USA', 'UK', 'Frn'], dtype='object')
['Del' 'DC' 'London' 'paris']
None
(4,)
4
False
False
True
1

In [210]:
#Methods
print(New)
print(New.head(2))
print(New.tail(2))
print(S_sclar.describe())
print(S_sclar.value_counts())
print(S_sclar.sort_values())
print(S_sclar.sort_index())
print(S_sclar.drop('a'))
print(S_sclar.replace('b','g'))
print(S_sclar.isnull())
print(S_sclar.notnull())

Ind       Del
USA        DC
UK     London
Frn     paris
dtype: object
Ind    Del
USA     DC
dtype: object
UK     London
Frn     paris
dtype: object
count     5.0
mean     10.0
std       0.0
min      10.0
25%      10.0
50%      10.0
75%      10.0
max      10.0
dtype: float64
10    5
Name: count, dtype: int64
a    10
b    10
c    10
d    10
e    10
dtype: int64
a    10
b    10
c    10
d    10
e    10
dtype: int64
b    10
c    10
d    10
e    10
dtype: int64
a    10
b    10
c    10
d    10
e    10
dtype: int64
a    False
b    False
c    False
d    False
e    False
dtype: bool
a    True
b    True
c    True
d    True
e    True
dtype: bool

In [211]:
#Dataframe
Empty_df = pd.DataFrame()
print(Empty_df)

Empty DataFrame
Columns: []
Index: []

In [212]:
data = [{'name':'Vamshi','age':20,'city':'Hyd'},{'name':'Sai','age':30,'city':'Kol'},{'name':'Richa','age':27,'city':'Del'}]
data_frame = pd.DataFrame(data)
print(data_frame)

     name  age city
0  Vamshi   20  Hyd
1     Sai   30  Kol
2   Richa   27  Del

In [213]:
data_frame['name']

0    Vamshi
1       Sai
2     Richa
Name: name, dtype: object

In [214]:
data_frame[['name','city']]

     name city
0  Vamshi  Hyd
1     Sai  Kol
2   Richa  Del

In [215]:
data_frame.loc[2]

name    Richa
age        27
city      Del
Name: 2, dtype: object

In [216]:
data_frame.iloc[0]

name    Vamshi
age         20
city       Hyd
Name: 0, dtype: object

In [217]:
male_cust=data_frame[data_frame['name']=='Vamshi']
print(male_cust)

     name  age city
0  Vamshi   20  Hyd

In [218]:
male_cust=data_frame[(data_frame['name']=='Vamshi')|(data_frame['city']=='Hyd')]
print(male_cust)

     name  age city
0  Vamshi   20  Hyd

In [219]:
#Silicing
print(data_frame[:1])
print(data_frame.loc[:2,['name','city']])
print(data_frame.loc[:2,:])
print(data_frame.iloc[:1,1:])

     name  age city
0  Vamshi   20  Hyd
     name city
0  Vamshi  Hyd
1     Sai  Kol
2   Richa  Del
     name  age city
0  Vamshi   20  Hyd
1     Sai   30  Kol
2   Richa   27  Del
   age city
0   20  Hyd

In [220]:
print(data_frame.index)
print(data_frame.shape)
print(data_frame.columns)
print(data_frame.dtypes)
print(data_frame.values)
print(data_frame.size)
print(data_frame.empty)
print(data_frame.ndim)
print(data_frame.isnull())
print(data_frame.isna())
print(data_frame.style)
print(data_frame.loc)
print(data_frame.iloc)
print(data_frame.memory_usage)
print(data_frame.info())

RangeIndex(start=0, stop=3, step=1)
(3, 3)
Index(['name', 'age', 'city'], dtype='object')
name    object
age      int64
city    object
dtype: object
[['Vamshi' 20 'Hyd']
 ['Sai' 30 'Kol']
 ['Richa' 27 'Del']]
9
False
2
    name    age   city
0  False  False  False
1  False  False  False
2  False  False  False
    name    age   city
0  False  False  False
1  False  False  False
2  False  False  False
<pandas.io.formats.style.Styler object at 0x000001AB17E73080>
<pandas.core.indexing._LocIndexer object at 0x000001AB1931CC30>
<pandas.core.indexing._iLocIndexer object at 0x000001AB1931CC30>
<bound method DataFrame.memory_usage of      name  age city
0  Vamshi   20  Hyd
1     Sai   30  Kol
2   Richa   27  Del>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

In [221]:
print(data_frame.tail(1))
print(data_frame.head(1))
print(data_frame.describe())
print(data_frame.transpose())

    name  age city
2  Richa   27  Del
     name  age city
0  Vamshi   20  Hyd
             age
count   3.000000
mean   25.666667
std     5.131601
min    20.000000
25%    23.500000
50%    27.000000
75%    28.500000
max    30.000000
           0    1      2
name  Vamshi  Sai  Richa
age       20   30     27
city     Hyd  Kol    Del

In [222]:
#Adding values
data_frame['country']='IND'
data_frame

     name  age city country
0  Vamshi   20  Hyd     IND
1     Sai   30  Kol     IND
2   Richa   27  Del     IND

In [223]:
Meb_status = ['Gold','Silver','Bronze']
data_frame['Meb_stat'] = Meb_status
data_frame

     name  age city country Meb_stat
0  Vamshi   20  Hyd     IND     Gold
1     Sai   30  Kol     IND   Silver
2   Richa   27  Del     IND   Bronze

In [224]:
#Adding Row wise
data_frame.loc['3']= ['Ravi',37,'Bng','IND','Silver']
data_frame

     name  age city country Meb_stat
0  Vamshi   20  Hyd     IND     Gold
1     Sai   30  Kol     IND   Silver
2   Richa   27  Del     IND   Bronze
3    Ravi   37  Bng     IND   Silver

In [225]:
#Deleting row
data_frame.drop(index = data_frame.index[3])

     name  age city country Meb_stat
0  Vamshi   20  Hyd     IND     Gold
1     Sai   30  Kol     IND   Silver
2   Richa   27  Del     IND   Bronze

In [226]:
#Rename the col name
data_frame.rename(index = {0:'S.NO'})

        name  age city country Meb_stat
S.NO  Vamshi   20  Hyd     IND     Gold
1        Sai   30  Kol     IND   Silver
2      Richa   27  Del     IND   Bronze
3       Ravi   37  Bng     IND   Silver

In [227]:
#Rename Muliple Col names
data_frame.rename(columns = {'name':'Firstname','Meb_stat':'Award'})

  Firstname  age city country   Award
0    Vamshi   20  Hyd     IND    Gold
1       Sai   30  Kol     IND  Silver
2     Richa   27  Del     IND  Bronze
3      Ravi   37  Bng     IND  Silver

In [228]:
data_frame['country'].unique()

array(['IND'], dtype=object)

In [229]:
data_frame['age']=data_frame['age'].astype(float)
data_frame

     name   age city country Meb_stat
0  Vamshi  20.0  Hyd     IND     Gold
1     Sai  30.0  Kol     IND   Silver
2   Richa  27.0  Del     IND   Bronze
3    Ravi  37.0  Bng     IND   Silver

In [230]:
data_frame1 = data_frame

In [231]:
data_frame1

     name   age city country Meb_stat
0  Vamshi  20.0  Hyd     IND     Gold
1     Sai  30.0  Kol     IND   Silver
2   Richa  27.0  Del     IND   Bronze
3    Ravi  37.0  Bng     IND   Silver

In [232]:
data_frame

     name   age city country Meb_stat
0  Vamshi  20.0  Hyd     IND     Gold
1     Sai  30.0  Kol     IND   Silver
2   Richa  27.0  Del     IND   Bronze
3    Ravi  37.0  Bng     IND   Silver

In [233]:
pd.concat([data_frame1,data_frame],axis = 0)

     name   age city country Meb_stat
0  Vamshi  20.0  Hyd     IND     Gold
1     Sai  30.0  Kol     IND   Silver
2   Richa  27.0  Del     IND   Bronze
3    Ravi  37.0  Bng     IND   Silver
0  Vamshi  20.0  Hyd     IND     Gold
1     Sai  30.0  Kol     IND   Silver
2   Richa  27.0  Del     IND   Bronze
3    Ravi  37.0  Bng     IND   Silver

In [234]:
#Concat
pd.concat([data_frame1,data_frame],axis = 1)

     name   age city country Meb_stat    name   age city country Meb_stat
0  Vamshi  20.0  Hyd     IND     Gold  Vamshi  20.0  Hyd     IND     Gold
1     Sai  30.0  Kol     IND   Silver     Sai  30.0  Kol     IND   Silver
2   Richa  27.0  Del     IND   Bronze   Richa  27.0  Del     IND   Bronze
3    Ravi  37.0  Bng     IND   Silver    Ravi  37.0  Bng     IND   Silver

In [235]:
new = [{'name':'Vamshi','sal':400000},{'name':'Sai','sal':480000},{'name':'Richa','sal':500000}]
new1 = pd.DataFrame(new)
new1

     name     sal
0  Vamshi  400000
1     Sai  480000
2   Richa  500000

In [236]:
#Merge
pd.merge(data_frame,new1,on='name',how='inner')

     name   age city country Meb_stat     sal
0  Vamshi  20.0  Hyd     IND     Gold  400000
1     Sai  30.0  Kol     IND   Silver  480000
2   Richa  27.0  Del     IND   Bronze  500000

In [237]:
pd.merge(data_frame,new1,on='name',how='outer')

     name   age city country Meb_stat       sal
0    Ravi  37.0  Bng     IND   Silver       NaN
1   Richa  27.0  Del     IND   Bronze  500000.0
2     Sai  30.0  Kol     IND   Silver  480000.0
3  Vamshi  20.0  Hyd     IND     Gold  400000.0

In [238]:
pd.merge(data_frame,new1,on='name',how='left')

     name   age city country Meb_stat       sal
0  Vamshi  20.0  Hyd     IND     Gold  400000.0
1     Sai  30.0  Kol     IND   Silver  480000.0
2   Richa  27.0  Del     IND   Bronze  500000.0
3    Ravi  37.0  Bng     IND   Silver       NaN

In [239]:
pd.merge(data_frame,new1,on='name',how='right')

     name   age city country Meb_stat     sal
0  Vamshi  20.0  Hyd     IND     Gold  400000
1     Sai  30.0  Kol     IND   Silver  480000
2   Richa  27.0  Del     IND   Bronze  500000

In [240]:
#Finding missing values
confirmed_cases = pd.read_csv('covid_19_confirmed_v1.csv')

In [241]:
confirmed_cases.isnull().sum()

Province/State    190
Country/Region      0
Lat                 2
Long                2
1/22/20             0
                 ...
5/25/21             0
5/26/21             0
5/27/21             0
5/28/21             0
5/29/21             0
Length: 498, dtype: int64

In [242]:
confirmed_cases.isna().sum()

Province/State    190
Country/Region      0
Lat                 2
Long                2
1/22/20             0
                 ...
5/25/21             0
5/26/21             0
5/27/21             0
5/28/21             0
5/29/21             0
Length: 498, dtype: int64

In [243]:
confirmed_cases.isnull().any()

Province/State     True
Country/Region    False
Lat                True
Long               True
1/22/20           False
                  ...
5/25/21           False
5/26/21           False
5/27/21           False
5/28/21           False
5/29/21           False
Length: 498, dtype: bool

In [244]:
confirmed_cases.isnull().any().any()

True

In [245]:
confirmed_cases.isnull().sum()

Province/State    190
Country/Region      0
Lat                 2
Long                2
1/22/20             0
                 ...
5/25/21             0
5/26/21             0
5/27/21             0
5/28/21             0
5/29/21             0
Length: 498, dtype: int64

In [246]:
confirmed_cases['Province/State']=confirmed_cases['Province/State'].replace('unknown',pd.NA)

In [247]:
confirmed_cases.fillna('Unknown',inplace=True)

C:\Users\VamC\AppData\Local\Temp\ipykernel_15076\2122419334.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  confirmed_cases.fillna('Unknown',inplace=True)

In [248]:
confirmed_cases

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21,5/28/21,5/29/21
0,Unknown,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,64575,65080,65486,65728,66275,66903,67743,68366,69130,70111
1,Unknown,Albania,41.1533,20.1683,0,0,0,0,0,0,...,132118,132153,132176,132209,132215,132229,132244,132264,132285,132297
2,Unknown,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,126156,126434,126651,126860,127107,127361,127646,127926,128198,128456
3,Unknown,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,13569,13569,13569,13569,13569,13664,13671,13682,13693,13693
4,Unknown,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,31661,31909,32149,32441,32623,32933,33338,33607,33944,34180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,Unknown,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,4809,4941,5119,5275,5404,5931,6086,6356,6396,6908
272,Unknown,West Bank and Gaza,31.9522,35.2332,0,0,0,0,0,0,...,304532,304968,305201,305201,305777,306334,306795,306795,307569,307838
273,Unknown,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,6613,6632,6649,6658,6662,6670,6688,6696,6723,6731
274,Unknown,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,92754,92920,93106,93201,93279,93428,93627,93947,94430,94751
275,Unknown,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,38635,38664,38679,38682,38696,38706,38819,38854,38918,38933

In [249]:
confirmed_cases.drop_duplicates(inplace=False,subset=None)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,5/20/21,5/21/21,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21,5/28/21,5/29/21
0,Unknown,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,64575,65080,65486,65728,66275,66903,67743,68366,69130,70111
1,Unknown,Albania,41.1533,20.1683,0,0,0,0,0,0,...,132118,132153,132176,132209,132215,132229,132244,132264,132285,132297
2,Unknown,Algeria,28.0339,1.6596,0,0,0,0,0,0,...,126156,126434,126651,126860,127107,127361,127646,127926,128198,128456
3,Unknown,Andorra,42.5063,1.5218,0,0,0,0,0,0,...,13569,13569,13569,13569,13569,13664,13671,13682,13693,13693
4,Unknown,Angola,-11.2027,17.8739,0,0,0,0,0,0,...,31661,31909,32149,32441,32623,32933,33338,33607,33944,34180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,Unknown,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,4809,4941,5119,5275,5404,5931,6086,6356,6396,6908
272,Unknown,West Bank and Gaza,31.9522,35.2332,0,0,0,0,0,0,...,304532,304968,305201,305201,305777,306334,306795,306795,307569,307838
273,Unknown,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,6613,6632,6649,6658,6662,6670,6688,6696,6723,6731
274,Unknown,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,92754,92920,93106,93201,93279,93428,93627,93947,94430,94751
275,Unknown,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,38635,38664,38679,38682,38696,38706,38819,38854,38918,38933

In [250]:
#agg_pair=confirmed_cases.groupby('Country/Region').agg({'Lat':'max','Long':'max'})

In [251]:
df = pd.read_csv(r'data/application.csv')

In [252]:
df

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,384575,0,Cash loans,M,Y,N,2,207000.0,465457.5,52641.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
1,214010,0,Cash loans,F,Y,Y,0,247500.0,1281712.5,48946.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
2,142232,0,Cash loans,F,Y,N,0,202500.0,495000.0,39109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
3,389171,0,Cash loans,F,N,Y,0,247500.0,254700.0,24939.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,283617,0,Cash loans,M,N,Y,0,112500.0,308133.0,15862.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15371,406895,0,Cash loans,F,Y,Y,1,112500.0,406597.5,31594.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
15372,376623,0,Cash loans,F,N,Y,0,112500.0,254700.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15373,273086,0,Cash loans,M,N,Y,0,121360.5,1080000.0,29700.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
15374,160442,0,Cash loans,F,Y,Y,0,90000.0,526491.0,32337.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
15375,171598,0,Cash loans,M,N,N,0,135000.0,592560.0,32274.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

In [253]:
df.fillna(method = 'ffill',inplace = True)

C:\Users\VamC\AppData\Local\Temp\ipykernel_15076\3028625988.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill',inplace = True)

In [254]:
df.isnull().sum()

SK_ID_CURR                    0
TARGET                        0
NAME_CONTRACT_TYPE            0
CODE_GENDER                   0
FLAG_OWN_CAR                  0
                             ..
AMT_REQ_CREDIT_BUREAU_DAY     0
AMT_REQ_CREDIT_BUREAU_WEEK    0
AMT_REQ_CREDIT_BUREAU_MON     0
AMT_REQ_CREDIT_BUREAU_QRT     0
AMT_REQ_CREDIT_BUREAU_YEAR    0
Length: 122, dtype: int64

In [255]:
df['AMT_INCOME_TOTAL'].mean()

175875.80018015087

In [256]:
df['AMT_INCOME_TOTAL'].median()

148500.0

In [257]:
df['CODE_GENDER'].value_counts()

CODE_GENDER
F    10219
M     5157
Name: count, dtype: int64

In [258]:
df['AMT_INCOME_TOTAL'].max()

117000000.0

In [259]:
df['AMT_INCOME_TOTAL'].min()

27000.0

In [260]:
df['AMT_INCOME_TOTAL'].sum()

2704266303.5699997

In [261]:
df['AMT_INCOME_TOTAL'].agg(['max','min'])

max    117000000.0
min        27000.0
Name: AMT_INCOME_TOTAL, dtype: float64

In [262]:
df['SK_ID_CURR'].sort_values()

12943    100004
698      100020
7619     100029
13405    100035
6168     100056
          ...
3045     456072
6033     456142
7093     456228
3769     456238
11798    456247
Name: SK_ID_CURR, Length: 15376, dtype: int64

In [263]:
df_new = df['AMT_ANNUITY'].idxmax()
print(df_new)

983

In [264]:
df['NAME_CONTRACT_TYPE'].value_counts()

NAME_CONTRACT_TYPE
Cash loans         13939
Revolving loans     1437
Name: count, dtype: int64

In [265]:
group_values = df.groupby('NAME_CONTRACT_TYPE')
print(group_values['AMT_INCOME_TOTAL'].mean())
print(group_values['AMT_INCOME_TOTAL'].sum())

NAME_CONTRACT_TYPE
Cash loans         177151.967291
Revolving loans    163496.890397
Name: AMT_INCOME_TOTAL, dtype: float64
NAME_CONTRACT_TYPE
Cash loans         2.469321e+09
Revolving loans    2.349450e+08
Name: AMT_INCOME_TOTAL, dtype: float64

In [266]:
df.groupby('NAME_CONTRACT_TYPE')['AMT_CREDIT'].count()

NAME_CONTRACT_TYPE
Cash loans         13939
Revolving loans     1437
Name: AMT_CREDIT, dtype: int64

In [337]:
df2

  region Product  Sales
0   East       A    100
1   West       A    150
2   East       B    200
3   West       B    250
4   East       C    300
5   West       C    350

In [339]:
data = {'region':['East','West','East','West','East','West'],'Product':['A','A','B','B','C','C'],'Sales':[100,150,200,250,300,350]}
df2 = pd.DataFrame(data)

In [351]:
df2.pivot_table(values='Sales',index='region',columns='Product',aggfunc='sum')

Product    A    B    C
region
East     100  200  300
West     150  250  350

In [363]:
def cust_agg(x):
    return x.max()-x.min()

pivot = df2.pivot_table(values='Sales',index='region',columns='Product',aggfunc=cust_agg)
print(pivot)

Product  A  B  C
region
East     0  0  0
West     0  0  0

In [369]:
cross_table = pd.crosstab(df2['region'],df2['Product'])
print(cross_table)

Product  A  B  C
region
East     1  1  1
West     1  1  1

In [383]:
data1 = {
'Region': ['East', 'West'],
'Product_A': [100, 150],
'Product_B': [200, 250],
'Product_C': [300, 350]
}
df3 = pd.DataFrame(data1)
# Melting the DataFrame
melted_df = pd.melt(df3, id_vars=['Region'], value_vars=['Product_A', 'Product_B',
'Product_C'], var_name='Product', value_name='Sales')
print(melted_df)

  Region    Product  Sales
0   East  Product_A    100
1   West  Product_A    150
2   East  Product_B    200
3   West  Product_B    250
4   East  Product_C    300
5   West  Product_C    350

In [385]:
df.to_csv('output.csv', index=False)